PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>

SELECT ?datasetTitle ?model (COUNT(?provDist) AS ?provenanceFiles)
WHERE {
  ?dataset a dcat:Dataset ;
           dct:title ?datasetTitle ;
           dcat:distribution ?provDist .
  ?provDist dct:title ?distTitle ;
            dcat:downloadURL ?download .
  FILTER(CONTAINS(LCASE(STR(?distTitle)), "provenance"))

  BIND(STRBEFORE(STRAFTER(STR(?download), "/models/"), "/") AS ?model)
}
GROUP BY ?datasetTitle ?model
ORDER BY DESC(?provenanceFiles) ?datasetTitle ?model
