PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dsv: <https://w3id.org/dsv-ontology#>
PREFIX csvw: <http://www.w3.org/ns/csvw#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>

SELECT ?datasetLabel (COUNT(?col) AS ?columns)
WHERE {
  ?dataset a dcat:Dataset .
  OPTIONAL { ?dataset dct:title ?datasetTitle }
  BIND(COALESCE(?datasetTitle, STR(?dataset)) AS ?datasetLabel)

  OPTIONAL {
    ?dataset (dsv:datasetSchema|csvw:tableSchema|<https://schema.org/datasetSchema>|<http://schema.org/datasetSchema>) ?schema .
    ?schema (dsv:column|csvw:column|<https://schema.org/column>) ?col .
  }
}
GROUP BY ?datasetLabel
ORDER BY DESC(?columns)
